
-- Create user profiles table
CREATE TABLE IF NOT EXISTS public.user_profiles (
    profile_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    profile_bio text,
    profile_avatar character varying,
    profile_favorite_classification integer,
    profile_join_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_profiles_pkey PRIMARY KEY (profile_id)
);

-- Create foreign key relationship between profiles and accounts
ALTER TABLE IF EXISTS public.user_profiles
ADD CONSTRAINT fk_account FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON DELETE CASCADE;

-- Create achievements table
CREATE TABLE IF NOT EXISTS public.achievements (
    achievement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    achievement_name character varying NOT NULL,
    achievement_description text,
    achievement_icon character varying,
    achievement_points integer NOT NULL DEFAULT 0,
    CONSTRAINT achievements_pkey PRIMARY KEY (achievement_id)
);

-- Create user achievements table to link users to their earned achievements
CREATE TABLE IF NOT EXISTS public.user_achievements (
    user_achievement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    achievement_id integer NOT NULL,
    earned_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_achievements_pkey PRIMARY KEY (user_achievement_id)
);

-- Create foreign key relationships for user_achievements
ALTER TABLE IF EXISTS public.user_achievements
ADD CONSTRAINT fk_account FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.user_achievements
ADD CONSTRAINT fk_achievement FOREIGN KEY (achievement_id)
REFERENCES public.achievements (achievement_id)
ON DELETE CASCADE;

-- Insert some default achievements
INSERT INTO public.achievements (achievement_name, achievement_description, achievement_icon, achievement_points) VALUES
('First Login', 'Logged into your account for the first time', 'fa-sign-in-alt', 10),
('Car Explorer', 'Viewed details of 5 different vehicles', 'fa-car', 20),
('Classification Expert', 'Viewed vehicles from all 5 classifications', 'fa-list-ul', 30),
('Account Verified', 'Verified your email address', 'fa-check-circle', 15),
('Profile Complete', 'Added a bio and avatar to your profile', 'fa-user-circle', 25);
